services:
  ruby-lambda-builder:
    build:
      context: ./infrastructure/docker/ruby-lambda-builder
      dockerfile: Dockerfile
    volumes:
      - ./lambda:/var/task
      - ./infrastructure/modules/lambda:/output
      - bundle_cache:/var/task/.bundle
    working_dir: /var/task
    security_opt:
      - no-new-privileges:true

volumes:
  bundle_cache:
    driver: local