source 'https://rubygems.org'

# AWS SDK
gem 'aws-sdk-dynamodb', '~> 1.0'
gem 'aws-sdk-lambda', '~> 1.0'
gem 'aws-sdk-secretsmanager', '~> 1.0'

# Google APIs
gem 'google-apis-drive_v3', '~> 0.44'
gem 'googleauth', '~> 1.8'
gem 'signet', '~> 0.17'

# Slack SDK
gem 'slack-ruby-client', '~> 2.0'

# HTTP Clients
gem 'faraday', '~> 2.0'
gem 'faraday-retry', '~> 2.0'

# Testing (development group)
group :development, :test do
  gem 'rspec', '~> 3.0'
  gem 'webmock', '~> 3.0'
  gem 'simplecov', '~> 0.22'
  gem 'rubocop', '~> 1.0'
  gem 'dotenv', '~> 2.8'
end